"""Add status to Topic

Revision ID: 4e738eacb825
Revises: a6dee41b51bf
Create Date: 2026-01-17 20:32:07.180526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e738eacb825'
down_revision: Union[str, Sequence[str], None] = 'a6dee41b51bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='topicstatus'), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'status')
    # ### end Alembic commands ###
